---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting-and-quality:
    name: Formatting and Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22

      # Evaluate the devshell here so that the time reported for subsequent
      # steps that use it reflect what is actually done there.
      - name: Evaluate devShell
        run: nix develop

      - name: Format
        run: nix develop --command treefmt --fail-on-change

      - name: Clippy
        run: nix develop --command cargo clippy --all-targets

      - name: Test
        run: nix build -L .#test

  build:
    name: Build
    needs:
      - formatting-and-quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22

      - name: Build
        run: nix build -L

      - name: Build and push container image
        if: ${{ github.ref_name == 'main' }}
        run: |
          local_cr="docker-archive://$(nix build .#container-image --no-link --print-out-paths)"
          remote_cr="docker://ghcr.io/dannixon/makerspace-spaceapi"

          skopeo copy --dest-creds="dannixon:${{ github.token }}" "$local_cr" "$remote_cr:${{ github.sha }}"
          skopeo copy --dest-creds="dannixon:${{ github.token }}" "$local_cr" "$remote_cr:latest"
